#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Border
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Alacritty desktop='^1'
bspc rule -a Qutebrowser desktop='^2'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Mpv desktop='^4'
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
xwallpaper --zoom /usr/share/backgrounds/wallpapers/0060.jpg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Emacs
emacs --daemon &
