# This is for configuring how many items to reach before 'scrolling' the view
# CURRENTLY DOES NOT WORK
scroll_offset = 6

# If joshuto does not know how to open the file, it can resort to opening it via xdg settings
xdg_open = true

# The maximum file size to show a preview for
# CURRENTLY DOES NOT WORK
max_preview_size = 2097152 # 2MB

[sort_option] 
show_icons = true 

# Configurations related to the display
[display]
# Collapse the preview window when there is no preview available
collapse_preview = true
# Ratios for parent view, current view and preview
column_ratio = [1, 3, 4]
# Show borders around different views
show_borders = true
# Show hidden files
show_hidden = false
# Show file icons (requires a supporting font)
# Show file previews
# CURRENTLY DOES NOT WORK
show_preview = true
# Shorten /home/$USER to ~
tilde_in_titlebar = true
# show directories first
directories_first = true
